<?php

namespace AppBundle\Repository;

/**
 * CriticsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriticsRepository extends \Doctrine\ORM\EntityRepository
{
}
